export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const REMOVE_PRODUCT_BASKET = 'REMOVE_PRODUCT_BASKET';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const GET_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_USER_INFO = 'SET_USER_INFO';
export const GET_USER_INFO = 'GET_USER_INFO';
export const SET_LAYOUT_CONFIG = 'SET_LAYOUT_CONFIG';
export const GET_LAYOUT_CONFIG = 'GET_LAYOUT_CONFIG';